In [7]:
import scipy
import random

import pandas as pd
from matplotlib import pyplot
from statsmodels.graphics.tsaplots import plot_acf

import itertools
import random
import numpy as np
import random
from datetime import datetime

import itertools 
import numpy as np
from itertools import product

case_type = 1
num_input_nodes = 3 
num_output_nodes = 2
num_patterns = 3
sequence_length = 2
sparsity_length = 1
sparsity_erratic = 0    
random_seed = datetime.now().timestamp()
binary_input = 1

num_hidden_layers = 1
network_type = "lstm"
training_alg = "adam"
activation_function = "tanh"
architecture = [num_input_nodes, 20, 9, 5, num_output_nodes]
batch_size = 10

# Generate binary input sequences

In [8]:
def generate_bit_patterns(bit_length=3):
    unique_input_patterns = []

    for bits in product([0, 1], repeat=bit_length):
        single_input = [bit for bit in bits]
        unique_input_patterns.append(single_input)
    return unique_input_patterns
generate_bit_patterns(bit_length=num_input_nodes)

[[0, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 1],
 [1, 0, 0],
 [1, 0, 1],
 [1, 1, 0],
 [1, 1, 1]]

# Make patterns of sequence length 

In [9]:
def generate_set(input_length=3, sequence_length =3, num_patterns=3):
    possible_inputs = generate_bit_patterns(input_length)
    all_available_patterns = list(itertools.permutations(possible_inputs, sequence_length))
    index_of_set = random.sample(range(0, len(all_available_patterns)), num_patterns)
    patterns_to_identify = [all_available_patterns[i] for i in index_of_set]
    random_patterns = [x for x in all_available_patterns if x not in patterns_to_identify]
    return np.array(patterns_to_identify), np.array(random_patterns), np.array(all_available_patterns)

patterns_to_identify, random_patterns, all_available_patterns = generate_set(num_input_nodes, 
                                                                             sequence_length, 
                                                                             num_patterns)
# corresponding_output, random_output, all_available_output = generate_set(num_ouput_nodes, 1, num_patterns)

print(len(patterns_to_identify), len(random_patterns), len(all_available_patterns))
# print(len(corresponding_output), len(random_output), len(all_available_output))
patterns_to_identify

3 53 56


array([[[0, 0, 0],
        [0, 1, 1]],

       [[0, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [0, 1, 0]]])

In [62]:
train_input = []
train_output = []
patterns_counter = 0
random.seed(10)
batch_counter = 0 
sparsity_length = 1
for i in range(100):
    if i % (sparsity_length+1) == 0:
        index = random.randint(0, num_patterns-1)
        train_input.append(patterns_to_identify[index])
        for o in range(sequence_length-1):
            train_output.append(np.array([0]*num_output_nodes))
        train_output.append(np.array([1]*num_output_nodes))
    else:
        
        index = random.randint(0, len(random_patterns)-1)
        train_input.append(random_patterns[index])
        for o in range(sequence_length):
            train_output.append(np.array([0]*num_output_nodes))
        
train_input = np.array(train_input)
train_input = train_input.reshape(train_input.shape[1]*train_input.shape[0], train_input.shape[2])

for i in range(len(train_input)):
    print(train_input[i], train_output[i])
    
print(len(train_input), len(train_output))


[1 0 0] [0 0]
[0 1 0] [1 1]
[0 0 0] [0 0]
[1 0 0] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[1 0 0] [0 0]
[1 1 0] [0 0]
[1 0 0] [0 0]
[0 1 0] [1 1]
[0 0 0] [0 0]
[0 0 1] [0 0]
[0 0 0] [0 0]
[0 1 1] [1 1]
[1 0 0] [0 0]
[1 0 1] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[1 1 1] [0 0]
[1 1 0] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[1 1 0] [0 0]
[0 1 0] [0 0]
[0 0 0] [0 0]
[0 1 1] [1 1]
[0 0 0] [0 0]
[1 0 0] [0 0]
[1 0 0] [0 0]
[0 1 0] [1 1]
[1 0 0] [0 0]
[1 1 1] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[0 0 0] [0 0]
[1 1 0] [0 0]
[0 0 0] [0 0]
[0 1 1] [1 1]
[1 1 1] [0 0]
[0 0 1] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[0 0 0] [0 0]
[1 0 0] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[0 0 1] [0 0]
[0 1 1] [0 0]
[1 0 0] [0 0]
[0 1 0] [1 1]
[0 1 1] [0 0]
[0 1 0] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[1 0 0] [0 0]
[0 0 0] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[1 1 1] [0 0]
[1 1 0] [0 0]
[1 0 0] [0 0]
[0 1 0] [1 1]
[0 1 0] [0 0]
[1 0 0] [0 0]
[0 1 1] [0 0]
[1 1 1] [1 1]
[0 0 1] [0 0]
[1 1 0] [0 0]
[1 0 0] [0 0]
[0 1 0] [1 1]
[0 1 0] [0 0]
[1 1 1

In [67]:
train_input_batched = []
train_output_batched = []

t = []
o = []

batch_size_ = batch_size * sequence_length
for i in range(len(train_input)):
    if i % batch_size_ == 0:
        t = []
        o = []
        train_input_batched.append(t)
        train_output_batched.append(o)    
    t.append(train_input[i])
    o.append(train_output[i])
train_input_batched = np.array(train_input_batched)
train_output_batched = np.array(train_output_batched)
print(train_input_batched.shape, train_output_batched.shape)

(10, 20, 3) (10, 20, 2)


In [65]:
# rows, timesteps, columns
print(batch_size_, batch_size, sequence_length)
train_input_batched[0]

20 10 2


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 0]])

In [ ]:
from pandas import DataFrame
from pandas import concat
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

n_epoch = 10


model = Sequential()
model.add(LSTM(num_input_nodes, batch_input_shape=(batch_size, 
                                                   train_input_batched.shape[1], 
                                                   train_input_batched.shape[2]), stateful=True))
model.add(Dense(num_output_nodes))
model.compile(loss='mean_squared_error', optimizer='adam')

# fit network
for i in range(n_epoch):
    model.fit(train_input_batched, train_output_batched, epochs=1, batch_size=batch_size, verbose=1, shuffle=False)
    model.reset_states()



In [81]:
from pandas import DataFrame
from pandas import concat
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
# create sequence
length = 10
sequence = [i/float(length) for i in range(length)]
# create X/y pairs
df = DataFrame(sequence)
df = concat([df, df.shift(1)], axis=1)
df.dropna(inplace=True)
# convert to LSTM friendly format
values = df.values
X, y = values[:, 0], values[:, 1]
t = np.array([[i,i] for i in y])
X = X.reshape(len(X), 1, 1)
# configure network
n_batch = 1
n_epoch = 10
n_neurons = 10
# design network
model = Sequential()
model.add(LSTM(n_neurons, batch_input_shape=(n_batch, X.shape[1], X.shape[2]), stateful=True))
model.add(Dense(2))
model.compile(loss='mean_squared_error', optimizer='adam')
# fit network
for i in range(n_epoch):
    model.fit(X, t, epochs=1, batch_size=n_batch, verbose=1, shuffle=False)
    model.reset_states()
# online forecast
for i in range(len(X)):
    testX, testy = X[i], t[i]
    testX = testX.reshape(1, 1, 1)
    yhat = model.predict(testX, batch_size=1)
    print('>Expected=%.1f, Predicted=%.1f' % (testy, yhat))


IndexError: tuple index out of range

In [74]:
print(X.shape, y.shape)

(9, 1, 1) (9,)


(9, 2)